data_path: '../Dataset/'
dataset: 'beauty'
search_depth: 1
train_num: 50

#Expand parameterwo
batch_size: 16
error_batch_size: 16
num_feedbacks: 2
steps_per_gradient: 1
addition_sample: 2
num_candidates: 8

#Select parameter
beam_width: 3
time_steps: 1
explore_param: 2 
sample_num: 32

#Reward
reward_func: 'ndcg' #ndcg

#Wandb parameter
use_wandb: True
wandb_api_key: ''

# Evaluate
metrics: ["hit","map","ndcg"]
model: "gpt-4o-mini"
seed: 42
candidate_size: 20
